source :rubygems
gem 'sinatra'
gem 'bencode'
gem 'base32'
gem 'rack'
gem 'bson_ext'
gem 'bundler'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'dm-constraints'
gem 'dm-pager'
#gem 'torrent-ruby', :git => 'git://github.com/mikhailvs/torrent-ruby.git'